package com.thalock.app.util

import android.content.Context
import com.thalock.app.data.model.Document
import java.io.File

object DocumentFileGenerator {

    /**
     * Generates a .txt file for the given document in the app's cache directory.
     * Returns the File object.
     */
    fun generateTextFile(context: Context, document: Document): File {
        val dir = File(context.cacheDir, "shared_docs")
        if (!dir.exists()) dir.mkdirs()

        val safeTitle = document.title.replace(Regex("[^a-zA-Z0-9._-]"), "_")
        val file = File(dir, "${safeTitle}_${document.id}.txt")

        val content = buildString {
            appendLine("=".repeat(40))
            appendLine(document.title)
            appendLine("=".repeat(40))
            appendLine()
            appendLine("Document Type: ${document.documentType.displayName}")
            document.country?.let { appendLine("Country: ${it.displayName}") }
            appendLine()
            appendLine("-".repeat(40))

            for (field in document.fields) {
                if (field.value.isNotBlank()) {
                    appendLine("${field.label}: ${field.value}")
                }
            }

            appendLine("-".repeat(40))
            appendLine()
            appendLine("Generated by ThaLock")
        }

        file.writeText(content)
        return file
    }

    /**
     * Cleans up old shared files from cache.
     */
    fun cleanCache(context: Context) {
        val dir = File(context.cacheDir, "shared_docs")
        if (dir.exists()) {
            dir.listFiles()?.forEach { it.delete() }
        }
    }
}
